config/routes.rb
Rails.application.routes.draw do

  root 'sessions#welcome'
  
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login route
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  #logout route
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  resources :topics
  resources :lists
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :liststop
  has_many :users, through: :lists

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :lists
  has_many :topics, through: :lists
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#helpers give access to methods in views
helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!session[:user_id]
  end

  def redirect_if_not_logged_in
    if !logged_in?
      redirect_to root_path
    end
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :redirect_if_not_logged_in
  def index
    @user = current_user
    @lists = List.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def welcome
    
  end

  def new
    
  end

  def create
    user = User.find_by(username: params[:user][:username])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to lists_path
    else
      flash[:message] = "Incorrect username or password, please try again."
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action: redirect_if_not_logged_in
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to lists_path
    else  
      render :new
    end
  end

  def show
    redirect_if_not_logged_in
    @user = User.find_by_id(params[:id])
  end

  private

  def user_params
      params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TopTenLists</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div> 
      <% if !logged_in? %>
        <%= link_to 'Log In', login_path %>
        <%= link_to 'Sign Up', signup_path %>
      <% else %>  
        <!-- <%= link_to 'Log Out', logout_path, method: "delete" %> -->
        <%= link_to 'My Account', user_path(current_user)%>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>All Posted Lists</h1>

<%= button_to 'Logout', logout_path, method: 'delete' %>

<%= link_to 'My Profile', user_path(@current_user)%>

app/views/users/new.html.erb
<h1>Become a TopTenLister!</h1>
<p>Sign up here:</p>

<%= form_for(@user, url: '/signup') do |f| %>

  <%= f.label :username, 'Username:'%>
  <%= f.text_field :username %> <br>

  <%= f.label :password, 'Password:' %>
  <%= f.password_field :password%> <br>
  <br>

  <%= f.submit 'Sign Up'%>

<% end %>

app/views/users/show.html.erb
<h1>Lists from <%=@user.username%></h1>

<%= button_to 'Logout', logout_path, method: 'delete' %>